### ISSUE TITLE
New Teacher Account Page: No validation

### ISSUE THREAD

**Issue by LopezJonathan** [TeamKismet/bit-286-mathgame#5]
Input text boxes don't have any validation or error handling. Currently, these text boxes can accept any input values including null values.

**Comment by LopezJonathan** [comment]
This issue has been resolved. New teacher account input fields now have validation for name and password.

**Comment by MikeTheGreat** [comment]
Is this for a particular page?

Bugs generally mean “There’s something wrong with X, specifically” rather than “We need this feature”

This seems like something that should go on in the Requirements doc, instead of a bug report.

Thanks!
--Mike
______________________________________________
Michael Panitz
Senior Founding Faculty II
P: 425.352.8211 | F: 425-352-8177
www.cascadia.edu<http://www.cascadia.edu/>

Due to Washington State's broad open records law most written communication to or from College employees is public record and available to the public and the media upon request.
Therefore this e-mail communication may be subject to public disclosure.

**Comment by LopezJonathan** [comment]
Ok, so this one could be changed to an enhancement rather than a bug and added to our Requirements document?
